# Generated by Django 4.1.1 on 2022-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='UUID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='UUID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
